/***
 * 地图瓦片枚举
 */
export enum TILE_TYPE_ENUM {
  WALL_ROW = 'WALL_ROW',
  WALL_COLUMN = 'WALL_COLUMN',
  WALL_LEFT_TOP = 'WALL_LEFT_TOP',
  WALL_RIGHT_TOP = 'WALL_RIGHT_TOP',
  WALL_LEFT_BOTTOM = 'WALL_LEFT_BOTTOM',
  WALL_RIGHT_BOTTOM = 'WALL_RIGHT_BOTTOM',
  CLIFF_LEFT = 'CLIFF_ROW_START',
  CLIFF_CENTER = 'CLIFF_ROW_CENTER',
  CLIFF_RIGHT = 'CLIFF_ROW_END',
  FLOOR = 'FLOOR',
}


export enum EVENT_ENUM {
  NEXT_LEVEL = 'NEXT_LEVEL',
  PLAYER_CTRL = 'PLAYER_CTRL',
  PLAYER_BORN = 'PLAYER_BORN',
  PLAYER_MOVE_END = 'PLAYER_MOVE_END',
  ATTACK_PLAYER = 'ATTACK_PLAYER',
  ATTACK_ENEMY ='ATTACK_ENEMY'
}


export enum CONTROLLER_NUM {
  TOP = 'TOP',
  RIGHT = 'RIGHT',
  LEFT = 'LEFT',
  BOTTOM = 'BOTTOM',
  TURN_LEFT = 'TURN_LEFT',
  TURN_RIGHT = 'TURN_RIGHT'
}

export enum FSM_PARAMS_TYPE_ENUM {
  NUMBER = 'NUMBER',
  TRIGGER = 'TRIGGER'
}

export enum PARAMS_NAME_ENUM {
  IDLE = 'IDLE',
  TURN_LEFT = 'TURN_LEFT',
  TURN_RIGHT = 'TURN_RIGHT',
  DIRECTION = 'DIRECTION',
  BLOCK_FRONT = 'BLOCK_FRONT',
  BLOCK_TURN_LEFT = 'BLOCK_TURN_LEFT',
  BLOCK_TURN_RIGHT = 'BLOCK_TURN_RIGHT',
  ATTACK = 'ATTACK',
  DEATH = 'DEATH',
}

export enum DIRECTION_ENUM {
  TOP = 'TOP',
  RIGHT = 'RIGHT',
  LEFT = 'LEFT',
  BOTTOM = 'BOTTOM',
}

export enum ENTITY_STATE_ENUM {
  IDLE = 'IDLE',
  TURN_LEFT = 'TURN_LEFT',
  TURN_RIGHT = 'TURN_RIGHT',
  BLOCK_FRONT = 'BLOCK_FRONT',
  BLOCK_TURN_LEFT = 'BLOCK_TURN_LEFT',
  BLOCK_TURN_RIGHT = 'BLOCK_TURN_RIGHT',
  ATTACK = 'ATTACK',
  DEATH = 'DEATH',
}

export enum DIRECTION_ORDER_ENUM {
  TOP = 0,
  RIGHT = 1,
  LEFT = 2,
  BOTTOM = 3,
}

export enum ENTITY_TYPE_ENUM {
  PLAYER = 'PLAYER'
}